#############################################################################
# Makefile for building: reach-can-agent
# Generated by qmake (2.01a) (Qt 4.8.4) on: Tue May 13 18:06:55 2014
# Project:  reach-can-agent.pro
# Template: app
# Command: /opt/reach/1.3.2/sysroots/i686-reachsdk-linux/usr/bin/qmake -o Makefile reach-can-agent.pro
#############################################################################

####### Compiler, tools and options

CC            = $(OE_QMAKE_CC)
CXX           = $(OE_QMAKE_CXX)
DEFINES       = 
CFLAGS        = -pipe -pipe $(OE_QMAKE_CFLAGS) -O2 -Wall -W -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -pipe -pipe $(OE_QMAKE_CFLAGS) $(OE_QMAKE_CXXFLAGS) -O2 -O2 -Wall -W -Wall -W -Wall -W $(DEFINES)
INCPATH       = -I/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/linux-g++ -I.
LINK          = $(OE_QMAKE_LINK)
LFLAGS        = $(OE_QMAKE_LDFLAGS)
LIBS          = $(SUBLIBS)    
AR            = $(OE_QMAKE_AR) cqs
RANLIB        = 
QMAKE         = /opt/reach/1.3.2/sysroots/i686-reachsdk-linux/usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = $(OE_QMAKE_STRIP)
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/can_agent.c \
		src/can_local.c \
		src/can_tio_socket.c \
		src/can_server_socket.c \
		src/logmsg.c 
OBJECTS       = can_agent.o \
		can_local.o \
		can_tio_socket.o \
		can_server_socket.o \
		logmsg.o
DIST          = /opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base.conf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base-unix.conf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++-unix.conf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf \
		reach-can-agent.pro
QMAKE_TARGET  = reach-can-agent
DESTDIR       = 
TARGET        = reach-can-agent

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: reach-can-agent.pro  /opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/linux-g++/qmake.conf /opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base.conf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base-unix.conf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++-unix.conf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf \
		/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile reach-can-agent.pro
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf:
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf:
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base.conf:
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base-unix.conf:
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++-unix.conf:
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri:
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf:
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf:
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf:
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf:
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf:
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf:
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf:
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf:
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf:
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf:
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf:
/opt/reach/1.3.2/sysroots/armv5te-reach-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile reach-can-agent.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/reach-can-agent1.0.0 || $(MKDIR) .tmp/reach-can-agent1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/reach-can-agent1.0.0/ && (cd `dirname .tmp/reach-can-agent1.0.0` && $(TAR) reach-can-agent1.0.0.tar reach-can-agent1.0.0 && $(COMPRESS) reach-can-agent1.0.0.tar) && $(MOVE) `dirname .tmp/reach-can-agent1.0.0`/reach-can-agent1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/reach-can-agent1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

can_agent.o: src/can_agent.c src/can_agent.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o can_agent.o src/can_agent.c

can_local.o: src/can_local.c src/can_agent.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o can_local.o src/can_local.c

can_tio_socket.o: src/can_tio_socket.c src/can_agent.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o can_tio_socket.o src/can_tio_socket.c

can_server_socket.o: src/can_server_socket.c src/can_agent.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o can_server_socket.o src/can_server_socket.c

logmsg.o: src/logmsg.c src/can_agent.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o logmsg.o src/logmsg.c

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

